# Generated by Django 4.1 on 2022-09-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='file',
            field=models.FileField(default='', upload_to='doc/', verbose_name=' پیوست : '),
        ),
    ]
