# Generated by Django 4.1 on 2022-09-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_letter_publishing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='delete_status',
            field=models.BooleanField(default=True, verbose_name=' بعد از یک سال پاک شود ؟ '),
        ),
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(max_length=255, verbose_name='توضیحات  '),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=50, verbose_name='موضوع  '),
        ),
    ]
