# Generated by Django 4.1 on 2022-09-09 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0005_alter_letter_delete_status_alter_letter_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='allow_for_l_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letter',
            name='allow_for_l_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='letter',
            name='allow_for_l_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Letter', to=settings.AUTH_USER_MODEL),
        ),
    ]
