# Generated by Django 4.1 on 2022-09-09 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letter', '0006_letter_allow_for_l_1_letter_allow_for_l_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ['-publishing_date']},
        ),
        migrations.AddField(
            model_name='letter',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letter',
            name='allow_for_l_1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='allow_for_l_2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='allow_for_l_3',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
