# Generated by Django 4.1 on 2022-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_letter_read_alter_letter_allow_for_l_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='replay',
            field=models.ManyToManyField(blank=True, null=True, related_name='letters', to='letter.letter'),
        ),
    ]
