# Generated by Django 4.1 on 2022-12-05 12:34

from django.db import migrations, models
import letter.validators


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0010_letter_reject_letter_reject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letter',
            name='file',
            field=models.FileField(blank='True', default='', upload_to='docs/', validators=[letter.validators.validate_file_extension], verbose_name=' پیوست : '),
        ),
    ]
