# Generated by Django 4.1 on 2022-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_myuser_groups_myuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_level_1',
            field=models.BooleanField(default=False, verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_level_2',
            field=models.BooleanField(default=False, verbose_name='مدیر عامل'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_level_3',
            field=models.BooleanField(default=False, verbose_name='کارمند'),
        ),
    ]
